name: Editors

on:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:

jobs:
  vscode:
    name: Visual Studio Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: editors/code
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run lint
      - run: npm run package
